force-app/main/default/objects/RealTimeDraw__e/RealTimeDraw__e.object-meta.xml
<CustomObject>
    <label>Real Time Draw</label>
    <pluralLabel>Real Time Draw</pluralLabel>
</CustomObject>

force-app/main/default/objects/RealTimeDraw__e/fields/LocalSessionId__c.field-meta.xml
<CustomField>
    <fullName>LocalSessionId__c</fullName>
    <label>Local Session</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RealTimeDraw__e/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>90000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RealTimeDrawConfig__mdt/RealTimeDrawConfig__mdt.object-meta.xml
<CustomObject>
    <label>Real Time Draw Config</label>
    <pluralLabel>Real Time Draw Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RealTimeDrawConfig__mdt/fields/InitialState__c.field-meta.xml
<CustomField>
    <fullName>InitialState__c</fullName>
    <label>Initial State</label>
    <length>90000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RealTimeController.cls
public with sharing class RealTimeController {
    @AuraEnabled(cacheable=true)
    public static String getInitialCanvasState() {
        RealTimeDrawConfig__mdt config = RealTimeDrawConfig__mdt.getInstance('Default');

        if (config != null && String.isNotBlank(config.InitialState__c)) {
            return config.InitialState__c;
        }

        return null;
    }

    @AuraEnabled(cacheable=false)
    public static String getSessionDetails() {
        String sessionId = UserInfo.getSessionId();

        if (String.isBlank(sessionId)) {
            return getTokenForUser();
        } else {
            return sessionId;
        }
    }

    @AuraEnabled
    public static void publishRealTimeDrawEvent(String compressedState, String localSessionId) {
        EventBus.publish(
            new RealTimeDraw__e(
                State__c = compressedState,
                LocalSessionId__c = localSessionId
            )
        );
    }

    private static String getTokenForUser() {
        String loginUrl = 'https://login.salesforce.com';
        String body = ''; // ...

        HttpRequest req = new HttpRequest();
        req.setEndpoint(loginUrl + '/services/oauth2/token');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        req.setBody(body);

        Http http = new Http();
        HttpResponse res = http.send(req);

        if (res.getStatusCode() == 200) {
            Map<String, Object> tokenMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            return (String) tokenMap.get('access_token');
        } else {
            throw new AuraHandledException('Failed to retrieve access token');
        }
    }
}